/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fastcreatorz.chatbotsusgi;

import java.awt.Image;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.ImageIcon;
import java.sql.Connection;  
import java.sql.DriverManager;  
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author sajjan
 */
public class login extends javax.swing.JFrame {
    
    /* Get project folder path */
    public String baseDir = System.getProperty("user.dir");
    /* Url Logo */
    public ImageIcon susLogo = new ImageIcon(new ImageIcon(baseDir + "/img/logo.png").getImage().getScaledInstance(64, 64, Image.SCALE_SMOOTH));
    /* Url Sign up icon */
    public ImageIcon signupIcon = new ImageIcon(new ImageIcon(baseDir + "/img/signup.png").getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH));
    /* Url Login icon */
    public ImageIcon loginIcon = new ImageIcon(new ImageIcon(baseDir + "/img/login.png").getImage().getScaledInstance(30, 25, Image.SCALE_SMOOTH));

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        
        /* Set Logo on top */
        labelLogo.setIcon(susLogo);

        /* Set Icon on Username */
        ImageIcon usernameIcon = new ImageIcon(new ImageIcon(baseDir + "/img/username.png").getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH));
        labelUserName.setIcon(usernameIcon);
        
        /* Set Icon on Password */
        ImageIcon passwordIcon = new ImageIcon(new ImageIcon(baseDir + "/img/password.png").getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH));
        labelPassword.setIcon(passwordIcon);
        
        /* Set Icon on login btn */
        btnLogin.setIcon(loginIcon);

        /* Set Icon on login btn */
        btnSignup.setIcon(signupIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLogo = new javax.swing.JLabel();
        labelUserName = new javax.swing.JLabel();
        fieldUserName = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnSignup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - Chat Bot By SUSGI");

        labelLogo.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        labelLogo.setForeground(new java.awt.Color(220, 33, 76));
        labelLogo.setText("Login - Chat Bot By SUSGI");

        labelUserName.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelUserName.setForeground(new java.awt.Color(220, 33, 76));
        labelUserName.setText(" ");

        fieldUserName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        fieldUserName.setToolTipText("Enter Your Username.");
        fieldUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldUserNameKeyPressed(evt);
            }
        });

        labelPassword.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(220, 33, 76));
        labelPassword.setText(" ");

        fieldPassword.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        fieldPassword.setToolTipText("Enter Your Password.");
        fieldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldPasswordKeyPressed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(220, 33, 76));
        btnLogin.setText("Log in");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        btnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLoginKeyPressed(evt);
            }
        });

        btnSignup.setBackground(new java.awt.Color(255, 255, 255));
        btnSignup.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(220, 33, 76));
        btnSignup.setText("Sign up");
        btnSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(labelLogo)
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSignup)
                        .addGap(74, 74, 74)
                        .addComponent(btnLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(labelUserName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(fieldUserName))))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelLogo)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUserName))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword)
                    .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        loginMethod();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginKeyPressed
        if (evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            loginMethod();
        }
    }//GEN-LAST:event_btnLoginKeyPressed

    private void fieldPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldPasswordKeyPressed
        if (evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            loginMethod();
        }
    }//GEN-LAST:event_fieldPasswordKeyPressed

    private void fieldUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldUserNameKeyPressed
        if (evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            loginMethod();
        }
    }//GEN-LAST:event_fieldUserNameKeyPressed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        this.setVisible(false);
        register RegisterPage = new register();
        RegisterPage.setVisible(true);
    }//GEN-LAST:event_btnSignupActionPerformed

    public void loginMethod(){
        String userName = fieldUserName.getText();
        String password = fieldPassword.getText();
                
        if (!userName.equals(" ") && !userName.equals("") && !password.equals(" ") && !password.equals("")){
            String encPassword = passwdEnc(password);
            matchCerds(userName, encPassword);
        }else{
//            JOptionPane.showMessageDialog(null, "Something wrong! Please try again");
            JOptionPane.showMessageDialog(null, "Dhayan Nal nai enter kita ja sakda!");
        }
    }
    public String passwdEnc(String password){
        /* Password Encryption  Method*/
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-512");
            md.update(password.getBytes());
            byte[] bytes = md.digest();
            StringBuilder sb = new StringBuilder();
            for(int i=0; i< bytes.length ;i++){
                sb.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));
            }

            return sb.toString();
        } 
        catch (NoSuchAlgorithmException e){
            System.out.println(e.getMessage());
            return null;
        }
        
    }
    
    public Connection dbConnection(){
        /* Create Connection with SQLite Database */
        try {
            Connection conn = DriverManager.getConnection("jdbc:sqlite:" + baseDir + "/db/db_login.db");
//            System.out.println("Connection to SQLite has been established.");
            return conn;
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            return null;
        }
    }
    
    public void matchCerds(String userName, String encPassword){
        /* Execute Query in Database */
        try {
            Connection conn = dbConnection();
            PreparedStatement pstmt = conn.prepareStatement("SELECT * FROM users WHERE username =? AND password=?");
            pstmt.setString(1, userName);  
            pstmt.setString(2, encPassword);  
            ResultSet res = pstmt.executeQuery();

            if(res.next()) {
                fieldUserName.setText("");
                fieldPassword.setText("");
                
                System.out.println("Login by user: "+ res.getString("name"));
//                JOptionPane.showMessageDialog(null, "Login done");
                home HomePage = new home();
                HomePage.setVisible(true);
                this.setVisible(false);
            }else{
                System.out.println("UserName or Password wrong! Please try again");
//                JOptionPane.showMessageDialog(null, "UserName or Password wrong! Please try again");
                JOptionPane.showMessageDialog(null, "Kuj yaad nai rakhya ja sakda!");

            }
            
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignup;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldUserName;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUserName;
    // End of variables declaration//GEN-END:variables
}
