/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fastcreatorz.chatbotsusgi;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author sajjan
 */
public class register extends javax.swing.JFrame {
    
    login LoginPage = new login();
    
    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        
        /* LoginClass Access baseDir Variable */
        String baseDir = LoginPage.baseDir;
        
        /* Set Logo on top */
        ImageIcon susLogo = LoginPage.susLogo;
        labelLogo.setIcon(susLogo);
        
        /* Set Icon on login btn */
        ImageIcon loginIcon = LoginPage.loginIcon;
        btnLogin.setIcon(loginIcon);

        /* Set Icon on login btn */
        ImageIcon signupIcon = LoginPage.signupIcon;
        btnSignup.setIcon(signupIcon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLogo = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        fieldUsername = new javax.swing.JTextField();
        labelUsername = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        btnSignup = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 400));

        labelLogo.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        labelLogo.setForeground(new java.awt.Color(220, 33, 76));
        labelLogo.setText("Login - Chat Bot By SUSGI");

        labelName.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelName.setForeground(new java.awt.Color(220, 33, 76));
        labelName.setText("Name:");

        labelUsername.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(220, 33, 76));
        labelUsername.setText("Username:");

        labelPassword.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(220, 33, 76));
        labelPassword.setText("Password:");

        btnSignup.setBackground(new java.awt.Color(255, 255, 255));
        btnSignup.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(220, 33, 76));
        btnSignup.setText("Sign up");
        btnSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(220, 33, 76));
        btnLogin.setText("Log in");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPassword)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSignup)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                .addComponent(btnLogin))
                            .addComponent(fieldPassword)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelName)
                            .addComponent(labelUsername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(fieldName))))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelLogo)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(labelLogo)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsername)
                    .addComponent(fieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword)
                    .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        String name = fieldName.getText();
        String userName = fieldUsername.getText();
        String password = fieldPassword.getText();
        if (!name.equals(" ") && !name.equals("") && !userName.equals(" ") && !userName.equals("") && !password.equals(" ") && !password.equals("")){
            String encPassword = LoginPage.passwdEnc(password);
            userInsertDB(name, userName, encPassword);
        }else{
//            JOptionPane.showMessageDialog(null, "Something wrong! Please try again");
            JOptionPane.showMessageDialog(null, "Dhayan Nal nai enter kita ja sakda!");
        }
        
    }//GEN-LAST:event_btnSignupActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        LoginPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLoginActionPerformed
    
    public void userInsertDB(String name, String userName, String encPassword){
        /* Execute Query in Database */
        try {
            Connection conn = LoginPage.dbConnection();
            PreparedStatement pstmt = conn.prepareStatement("INSERT INTO users(name, username, password) VALUES(?,?,?)");
            pstmt.setString(1, name);
            pstmt.setString(2, userName);
            pstmt.setString(3, encPassword);  
            int res = pstmt.executeUpdate();
            System.out.println("Res: " + res);
            if(res == 1) {
                fieldName.setText("");
                fieldUsername.setText("");
                fieldPassword.setText("");
                
                System.out.println("Signup Done");
                JOptionPane.showMessageDialog(null, "Signup Done");
//                JOptionPane.showMessageDialog(null, "Login done");
                LoginPage.setVisible(true);
                this.setVisible(false);
            }else{
//                System.out.println("UserName or Password wrong! Please try again");
//                JOptionPane.showMessageDialog(null, "UserName or Password wrong! Please try again");
                JOptionPane.showMessageDialog(null, "Kuj yaad nai rakhya ja sakda!");

            }
        }catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignup;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPassword;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUsername;
    // End of variables declaration//GEN-END:variables
}
